# Mini Training - Numpy and Pandas
Pandas and Numpy are 2 of the widely used python libraries in data science. They are very usely in 
big data. 


## 1- Numpy: Single and multi-dimensional numpy arrays
NumPy is a Linear Algebra Library used for multidimensional arrays
NumPy brings the best of two worlds: 
1. C/Fortran computational efficiency, 
2. Python language easy syntax 


\
**Let's define a one-dimensional array**

In [1]:
import numpy as np

In [2]:
list_1 = [10,20,30,40,50,60,70,80]
list_1

[10, 20, 30, 40, 50, 60, 70, 80]

\
**Let's create a numpy array from the list "my_list"**

In [3]:
my_array= np.array(list_1)
my_array

array([10, 20, 30, 40, 50, 60, 70, 80])

In [4]:
type(my_array)

numpy.ndarray

\
**Let's create Multi-dimensional (Matrix definition)** 

In [5]:
my_matrix =np.array([ [2, 5, 8], [7, 3, 6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

\
**Example 1: Write a code that creates the following 2x4 numpy array.**

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [6]:
# This is 4x4 matrix: 2 rows and 4 columns

x =np.array([ [3, 7, 9, 3], [4, 3, 2, 2]])
x

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

## 2- Numpy: Numpy built-in methods and functions

**"rand()" uniform distribution between 0 and 1**

In [7]:
x =np.random.rand(10)
x

array([0.06044536, 0.79976105, 0.97682622, 0.3956092 , 0.26506008,
       0.79417257, 0.43962778, 0.7244427 , 0.9889336 , 0.17466503])

\
**You can create a matrix of random number as well**

In [8]:
x =np.random.rand(4,2)
x

array([[0.11597859, 0.16692569],
       [0.95006512, 0.23281705],
       [0.1194171 , 0.58787202],
       [0.6452745 , 0.80023887]])

\
**"randint" is used to generate random integers between upper and lower bounds**

In [9]:
x =np.random.randint(1, 10)
x


1

In [10]:

### Generate 5 random between 1 and 50
for i in range(5):
    x=np.random.randint(1, 50)
    print(x)

40
45
19
43
1


\
**"randint" can be used to generate a certain number of random itegers as follows**


In [11]:
x=np.random.randint(1,60,5)
x

array([44, 15,  1, 36, 19], dtype=int32)

\
**np.arange creates an evenly spaced values within a given interval**

In [12]:
x =np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

\
**create a diagonal of ones and zeros everywhere else**

In [13]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

\
**Matrix of ones**

In [14]:
# Matrix of ones
x =np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

\
**Array of zeros**

In [15]:
x=np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

\
**For more to know: Google: Numpy nethod**

\
**Example 2: Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"**

In [ ]:
# np.arange() returns an evenly spaced values within a given interval
x = int(input("Enter a positive integer:"))
print(x)

x =np.random.randint(1, 10)
x

In [20]:
x =np.random.randint(1,x, 10)
x

array([9, 8, 2, 8, 5, 4, 5, 2, 6, 8], dtype=int32)

## 3- Perform Mathematical Operations in Numpy

In [21]:
# np.arange() returns anevenly spaced values within a given intenal
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# np.arange() returns anevenly spaced values within a given intenal
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
squared= x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
sqrt=np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
exp=np.exp(y)
exp

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

np.arange() returns evenly spaced values within a given interval

In [27]:

x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])


**Example 3:**
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]

Y = [9, 15, 4]
```

In [33]:
x=np.array([5, 7, 20])
y=np.array([5, 7, 20])

In [34]:
z=np.sqrt(x**2 + y**2)
z

array([ 7.07106781,  9.89949494, 28.28427125])

np.arange() returns an evenly spaced values within a given interval

In [35]:

y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Add 2 numpy arrays together

In [40]:
import numpy as np 
  
# create 2 arrays 
a = np.arange(4).reshape(2, 2) 
b = np.arange(4, 8).reshape(2, 2) 
  
# print 2 arrays 
print(a) 
print(b) 
  
# addition between 2 arrays 
print('--Addition--') 
print(a+b) 

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
--Addition--
[[ 4  6]
 [ 8 10]]


Use Squared

In [41]:
squared= x**2
squared

array([ 25,  49, 400])

In [42]:
sqrt=np.sqrt(squared)
sqrt

array([ 5.,  7., 20.])

In [43]:
exp=np.exp(y)
exp

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])


**Example 3: Given the X and Y values below, obtain the distance between them**

    X = [5, 7, 20]
    Y = [9, 15, 4]

In [45]:
x=np.array([5, 7, 20])
y=np.array([5, 7, 20])

z=np.sqrt(x**2 + y**2)
z

array([ 7.07106781,  9.89949494, 28.28427125])

In [46]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

## 3- Perform Mathematical operations in Numpy

In [47]:
my_np_array=np.array([2,5,6,8,9,7,1])
my_np_array

array([2, 5, 6, 8, 9, 7, 1])

In [48]:
# Access specific index from the numpy array
my_np_array[0]

np.int64(2)

In [49]:
# Access specific index from the numpy array
my_np_array[-1]


np.int64(1)

In [50]:
# Starting from the first index 0 up until and NOT including the last element
my_np_array[0:3]

array([2, 5, 6])

In [51]:
# Broadcasting, altering several values in a numpy array at once
my_np_array[0:4] =7
my_np_array

array([7, 7, 7, 7, 9, 7, 1])

In [52]:
# Let's define a two dimensional numpy array
matrix =np.random.randint(1,10,(4,4))
matrix

array([[4, 5, 9, 9],
       [6, 9, 3, 8],
       [3, 6, 5, 6],
       [7, 4, 6, 8]], dtype=int32)

In [53]:
# Get a row from a mtrix
matrix[0]

array([4, 5, 9, 9], dtype=int32)

In [54]:
# Get one element
matrix[0][0]

np.int32(4)


**Example 4: In the following matrix, replace the last row 0**.<br>
X =np.array([<br>[2, 30, 20, -2, -4],<br>
                    [3, 4,  40, -3, -2],<br>
                    [-3, 4, -6, 90, 10],<br>
                    [25, 45, 34, 22, 12],<br>
                    [13, 24, 22, 32, 37]])

In [55]:
X =np.array([[2, 30, 20, -2, -4], 
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10], 
             [25, 45, 34, 22, 12], 
             [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [56]:
X[4]=0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

## 4- Perform Array slicing and indexing

In [57]:
my_np_array=np.array([2,5,6,8,9,7,1])
my_np_array

array([2, 5, 6, 8, 9, 7, 1])

In [58]:
# Access specific index from the numpy array
my_np_array[0]

np.int64(2)

In [59]:
# Starting from the first index 0 up until and NOT including the last element
my_np_array[0:3]


array([2, 5, 6])

In [60]:
# Broadcasting, altering several values in a numpy array at once
my_np_array[0:4] =7
my_np_array

array([7, 7, 7, 7, 9, 7, 1])

In [61]:
# Let's define a two dimensional numpy array
matrix =np.random.randint(1,10,(4,4))
matrix

array([[1, 6, 2, 1],
       [2, 5, 5, 4],
       [6, 6, 2, 7],
       [7, 8, 9, 9]], dtype=int32)

In [62]:
# Get a row from a mtrix
matrix[0]

array([1, 6, 2, 1], dtype=int32)

In [63]:
# Get one element
matrix[0][0]

np.int32(1)

**Example 4:**
- In the following matrix, replace the last row 0
X =na.array([[2, 30, 20, -2, -4],
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])

In [64]:
X =np.array([[2, 30, 20, -2, -4],
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])

In [65]:
X[4]=0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

## 5- Perform Elements Selection (Conditional)

In [66]:
matrix =np.random.randint(1,10,(5,5))
matrix

array([[2, 2, 2, 9, 4],
       [3, 4, 2, 6, 1],
       [7, 8, 9, 6, 1],
       [1, 6, 6, 4, 5],
       [5, 6, 8, 2, 8]], dtype=int32)

In [67]:
new_matrix = matrix[ matrix >7]
new_matrix

array([9, 8, 9, 8, 8], dtype=int32)

In [68]:
# Obtain odd elements only
new_matrix = matrix[ matrix % 2 ==1]
new_matrix

array([9, 3, 1, 7, 9, 1, 1, 5, 5], dtype=int32)

**Example 5:**
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]

In [69]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24 ,22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [70]:
X[ X < 0] = 0
X[X%2 == 1] =-2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

## 6- Understand Pandas Fundamentals

In [71]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [72]:
import pandas as pd

In [73]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df =pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                           'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                           'Net Worth [$]': [3500, 4500, 10000, 20000],
                           'Years with bank': [3, 5, 9, 10]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve           4500                5
2             333            Mitch          10000                9
3             444             Ryan          20000               10

In [74]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [75]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve           4500                5

In [76]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan          20000               10

**Example 6:**
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [77]:
import pandas as pd;

portfolio_df= pd.DataFrame({'stock ticker symbol':['AAPL', 'AMZN', 'T'],
                            'price per share [$]':[3500, 200, 100],
                            'Number of stocks':[3, 4, 9]
                           })
portfolio_df

stock ticker symbol  price per share [$]  Number of stocks
0                AAPL                 3500                 3
1                AMZN                  200                 4
2                   T                  100                 9

In [78]:
stock_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
stock_dollar_value

0    10500
1      800
2      900
dtype: int64

In [79]:
stock_dollar_value.sum()

np.int64(12200)

## 7- Pandas with CSV AND HTML data
http://www.livingin-canada.com/house-prices-canada.html 

In [80]:
# Pandas is used to read a csv file and store data in a DataFrame

In [81]:
# Read tabular data using read_html
# After <read_> press TAB to check the options
house_price_df = pd.read_html("http://www.livingin-canada.com/house-prices-canada.html")
house_price_df[0]
# If not working: Run:  !pip install lxml
# !python -m pip install --upgrade pip

# First table



City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [82]:
# First table
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

**Example 7:**
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [83]:
retirement_df = pd.read_html("https://www.ssa.gov/oact/progdata/nra.html")
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

## 8- Pandas Operations

In [84]:
# Let's define a dataframe as follows:

bank_client_df =pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                           'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                           'Net Worth [$]': [3500, 4500, 10000, 20000],
                           'Years with bank': [3, 5, 9, 10]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve           4500                5
2             333            Mitch          10000                9
3             444             Ryan          20000               10

In [85]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[ bank_client_df["Years with bank"] >=5 ]
df_loyal

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
1             222            Steve           4500                5
2             333            Mitch          10000                9
3             444             Ryan          20000               10

In [86]:
# Delete a column from a DataFrame
 # del bank_client_df["Bank Client ID"]
 # bank_client_df

**Example 8:**
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [87]:
df_high_network = bank_client_df[  bank_client_df["Net Worth [$]"] >=5000 ]
df_high_network

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan          20000               10

In [88]:
df_high_network["Net Worth [$]"].sum()

np.int64(30000)

## 9: Pandas with Functions

In [89]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [90]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance*1.2

In [91]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [92]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

**Example 9:**
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [93]:
def networth_upate(balance):
    return balance * 3 + 200

In [94]:
results = bank_client_df['Net worth [$]'].apply(networth_update)

In [95]:
results

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [96]:
results.sum()

np.float64(53400.0)

## 10: Perform sorting and ordering in Pandas

In [97]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [98]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by='Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [99]:
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [100]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values(by= 'Years with bank', inplace = True)

In [101]:
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [102]:
# Set inplace = True to ensure that change has taken place in memory 


In [103]:
# Note that now the change (ordering) took place 

## 11: Perform concatenate and Merging with Pandas

In [104]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html


In [105]:
df1 = pd.DataFrame({  'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3'],
                      'C': ['C0', 'C1', 'C2', 'C3'],                            
                      'D': ['D0', 'D1', 'D2', 'D4']},
                    index = [0,1,2,3])

In [106]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D4

In [107]:
df2 = pd.DataFrame({  'A': ['A4', 'A5', 'A6', 'A7'],
                      'B': ['B4', 'B5', 'B6', 'B7'],
                      'C': ['C4', 'C5', 'C6', 'C7'],                            
                      'D': ['D4', 'D5', 'D6', 'D7']},
                      index = [4,5,6,7])

In [108]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [109]:
df3 = pd.DataFrame({  'A': ['A8', 'A9', 'A10', 'A11'],
                      'B': ['B8', 'B9', 'B10', 'B11'],
                      'C': ['C8', 'C9', 'C10', 'C11'],                            
                      'D': ['D8', 'D9', 'D10', 'D11']},
                    index = [8,9,10,11])

In [110]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [111]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D4
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

## PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [112]:

import pandas as pd

In [113]:
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 
raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [114]:

# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {'Bank Client ID': ['6', '7', '8', '9', '10'],
            'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
            'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [115]:
# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary

Bank Client ID  Annual Salary [$/year]
0              1                   25000
1              2                   35000
2              3                   45000
3              4                   48000
4              5                   49000
5              6                   32000
6              7                   33000
7              8                   34000
8              9                   23000
9             10                   22000

In [116]:
# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all



Bank Client ID First Name  Last Name
0              1      Nancy        Rob
1              2       Alex        Ali
2              3       Shep     George
3              4        Max      Mitch
4              5      Allen      Steve
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [117]:
# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

In [118]:
new_client = {'Bank Client ID': ['11'],
              'First Name': ['Ry'], 
              'Last Name': ['Aly'],
              'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [119]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000