# Mini Training - Numpy and Pandas
Pandas and Numpy are 2 of the widely used python libraries in data science. They are very usely in 
big data. 


## 1- Numpy: Single and multi-dimensional numpy arrays
NumPy is a Linear Algebra Library used for multidimensional arrays
NumPy brings the best of two worlds: 
1. C/Fortran computational efficiency, 
2. Python language easy syntax 


\
**Let's define a one-dimensional array**

In [ ]:
import numpy as np

In [ ]:
list_1 = [10,20,30,40,50,60,70,80]
list_1

\
**Let's create a numpy array from the list "my_list"**

In [ ]:
my_array= np.array(list_1)
my_array

In [ ]:
type(my_array)

\
**Let's create Multi-dimensional (Matrix definition)** 

In [ ]:
my_matrix =np.array([ [2, 5, 8], [7, 3, 6]])
my_matrix

\
**Example 1: Write a code that creates the following 2x4 numpy array.**

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
# This is 4x4 matrix: 2 rows and 4 columns

x =np.array([ [3, 7, 9, 3], [4, 3, 2, 2]])
x

## 2- Numpy: Numpy built-in methods and functions

**"rand()" uniform distribution between 0 and 1**

In [ ]:
x =np.random.rand(10)
x

\
**You can create a matrix of random number as well**

In [ ]:
x =np.random.rand(4,2)
x

\
**"randint" is used to generate random integers between upper and lower bounds**

In [ ]:
x =np.random.randint(1, 10)
x


In [ ]:

### Generate 5 random between 1 and 50
for i in range(5):
    x=np.random.randint(1, 50)
    print(x)

\
**"randint" can be used to generate a certain number of random itegers as follows**


In [ ]:
x=np.random.randint(1,60,5)
x

\
**np.arange creates an evenly spaced values within a given interval**

In [ ]:
x =np.arange(1, 50)
x

\
**create a diagonal of ones and zeros everywhere else**

In [ ]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(5)
x

\
**Matrix of ones**

In [ ]:
# Matrix of ones
x =np.ones((5,5))
x

\
**Array of zeros**

In [ ]:
x=np.zeros(8)
x

\
**For more to know: Google: Numpy nethod**

\
**Example 2: Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"**

In [ ]:
# np.arange() returns an evenly spaced values within a given interval
x = int(input("Enter a positive integer:"))
print(x)

x =np.random.randint(1, 10)
x

In [ ]:
x =np.random.randint(1,x, 10)
x

## 3- Perform Mathematical Operations in Numpy

In [ ]:
# np.arange() returns anevenly spaced values within a given intenal
x = np.arange(1,10)
x

In [ ]:
# np.arange() returns anevenly spaced values within a given intenal
y = np.arange(1,10)
y

In [ ]:
# Add 2 numpy arrays together
sum = x + y
sum

In [ ]:
squared= x**2
squared

In [ ]:
sqrt=np.sqrt(squared)
sqrt

In [ ]:
exp=np.exp(y)
exp

np.arange() returns evenly spaced values within a given interval

In [ ]:

x = np.arange(1,10)
x


**Example 3:**
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]

Y = [9, 15, 4]
```

In [ ]:
x=np.array([5, 7, 20])
y=np.array([5, 7, 20])

z=np.sqrt(x**2 + y**2)
z

np.arange() returns an evenly spaced values within a given interval

In [ ]:

y = np.arange(1,10)
y

Add 2 numpy arrays together

In [ ]:
sum = x + y
sum

Use Squared

In [ ]:
squared= x**2
squared

In [ ]:
sqrt=np.sqrt(squared)
sqrt

In [ ]:
exp=np.exp(y)
exp


**Example 3: Given the X and Y values below, obtain the distance between them**

    X = [5, 7, 20]
    Y = [9, 15, 4]

In [ ]:
x=np.array([5, 7, 20])
y=np.array([5, 7, 20])

z=np.sqrt(x**2 + y**2)
z

In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

## 3- Perform Mathematical operations in Numpy

In [ ]:
my_np_array=np.array([2,5,6,8,9,7,1])
my_np_array

In [ ]:
# Access specific index from the numpy array
my_np_array[0]

In [ ]:
# Access specific index from the numpy array
my_np_array[-1]


In [ ]:
# Starting from the first index 0 up until and NOT including the last element
my_np_array[0:3]

In [ ]:
# Broadcasting, altering several values in a numpy array at once
my_np_array[0:4] =7
my_np_array

In [ ]:
# Let's define a two dimensional numpy array
matrix =np.random.randint(1,10,(4,4))
matrix

In [ ]:
# Get a row from a mtrix
matrix[0]

In [ ]:
# Get one element
matrix[0][0]


**Example 4: In the following matrix, replace the last row 0**.<br>
X =np.array([<br>[2, 30, 20, -2, -4],<br>
                    [3, 4,  40, -3, -2],<br>
                    [-3, 4, -6, 90, 10],<br>
                    [25, 45, 34, 22, 12],<br>
                    [13, 24, 22, 32, 37]])

In [ ]:
X =np.array([[2, 30, 20, -2, -4], 
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10], 
             [25, 45, 34, 22, 12], 
             [13, 24, 22, 32, 37]])
X

In [ ]:
X[4]=0
X

## 4- Perform Array slicing and indexing

In [ ]:
my_np_array=np.array([2,5,6,8,9,7,1])
my_np_array

In [ ]:
# Access specific index from the numpy array
my_np_array[0]

In [ ]:
# Starting from the first index 0 up until and NOT including the last element
my_np_array[0:3]


In [ ]:
# Broadcasting, altering several values in a numpy array at once
my_np_array[0:4] =7
my_np_array

In [ ]:
# Let's define a two dimensional numpy array
matrix =np.random.randint(1,10,(4,4))
matrix

In [ ]:
# Get a row from a mtrix
matrix[0]

In [ ]:
# Get one element
matrix[0][0]

**Example 4:**
- In the following matrix, replace the last row 0
X =na.array([[2, 30, 20, -2, -4],
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])

In [ ]:
X =np.array([[2, 30, 20, -2, -4],
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])

In [ ]:
X[4]=0
X

## 5- Perform Elements Selection (Conditional)

In [ ]:
matrix =np.random.randint(1,10,(5,5))
matrix

In [ ]:
new_matrix = matrix[ matrix >7]
new_matrix

In [ ]:
# Obtain odd elements only
new_matrix = matrix[ matrix % 2 ==1]
new_matrix

**Example 5:**
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24 ,22, 32, 37]])
X

In [ ]:
X[ X < 0] = 0
X[X%2 == 1] =-2
X

## 6- Understand Pandas Fundamentals

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [ ]:
import pandas as pd

In [ ]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df =pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                           'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                           'Net Worth [$]': [3500, 4500, 10000, 20000],
                           'Years with bank': [3, 5, 9, 10]})
bank_client_df

In [ ]:
# Let's obtain the data type 
type(bank_client_df)

In [ ]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

In [ ]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

**Example 6:**
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
import pandas as pd;

portfolio_df= pd.DataFrame({'stock ticker symbol':['AAPL', 'AMZN', 'T'],
                            'price per share [$]':[3500, 200, 100],
                            'Number of stocks':[3, 4, 9]
                           })
portfolio_df

In [ ]:
stock_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
stock_dollar_value

In [ ]:
stock_dollar_value.sum()

## 7- Pandas with CSV AND HTML data
http://www.livingin-canada.com/house-prices-canada.html 

In [ ]:
# Pandas is used to read a csv file and store data in a DataFrame

In [ ]:
# Read tabular data using read_html
# After <read_> press TAB to check the options
house_price_df = pd.read_html("http://www.livingin-canada.com/house-prices-canada.html")
house_price_df[0]
# If not working: Run:  !pip install lxml
# !python -m pip install --upgrade pip

# First table



In [ ]:
# First table
house_price_df[1]

**Example 7:**
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
retirement_df = pd.read_html("https://www.ssa.gov/oact/progdata/nra.html")
retirement_df[0]

## 8- Pandas Operations

In [ ]:
# Let's define a dataframe as follows:

bank_client_df =pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                           'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                           'Net Worth [$]': [3500, 4500, 10000, 20000],
                           'Years with bank': [3, 5, 9, 10]})
bank_client_df

In [ ]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[ bank_client_df["Years with bank"] >=5 ]
df_loyal

In [ ]:
# Delete a column from a DataFrame
 # del bank_client_df["Bank Client ID"]
 # bank_client_df

**Example 8:**
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [148]:
df_high_network = bank_client_df[  bank_client_df["Net Worth [$]"] >=5000 ]
df_high_network

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan          20000               10

In [149]:
df_high_network["Net Worth [$]"].sum()

np.int64(30000)

## 9: Pandas with Functions

In [150]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [151]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance*1.2

In [152]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [153]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

**Example 9:**
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [154]:
def networth_upate(balance):
    return balance * 3 + 200

In [155]:
results = bank_client_df['Net worth [$]'].apply(networth_update)

In [156]:
results

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [157]:
results.sum()

np.float64(53400.0)

## 10: Perform sorting and ordering in Pandas

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by='Years with bank')

In [ ]:
bank_client_df

In [ ]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values(by= 'Years with bank', inplace = True)

In [ ]:
bank_client_df

In [ ]:
# Set inplace = True to ensure that change has taken place in memory 


In [ ]:
# Note that now the change (ordering) took place 

## 11: Perform concatenate and Merging with Pandas

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html


In [ ]:
df1 = pd.DataFrame({  'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3'],
                      'C': ['C0', 'C1', 'C2', 'C3'],                            
                      'D': ['D0', 'D1', 'D2', 'D4']},
                    index = [0,1,2,3])

In [ ]:
df1

In [ ]:
df2 = pd.DataFrame({  'A': ['A4', 'A5', 'A6', 'A7'],
                      'B': ['B4', 'B5', 'B6', 'B7'],
                      'C': ['C4', 'C5', 'C6', 'C7'],                            
                      'D': ['D4', 'D5', 'D6', 'D7']},
                      index = [4,5,6,7])

In [ ]:
df2

In [ ]:
df3 = pd.DataFrame({  'A': ['A8', 'A9', 'A10', 'A11'],
                      'B': ['B8', 'B9', 'B10', 'B11'],
                      'C': ['C8', 'C9', 'C10', 'C11'],                            
                      'D': ['D8', 'D9', 'D10', 'D11']},
                    index = [8,9,10,11])

In [ ]:
df3

In [ ]:
pd.concat([df1, df2, df3])

## PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [159]:

import pandas as pd

In [ ]:
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 
raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1

In [ ]:

# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {'Bank Client ID': ['6', '7', '8', '9', '10'],
            'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
            'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

In [ ]:
# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary

In [ ]:
# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all



In [ ]:
# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

In [ ]:
new_client = {'Bank Client ID': ['11'],
              'First Name': ['Ry'], 
              'Last Name': ['Aly'],
              'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df